import React, {useState} from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from "../components/Button";
import Link from 'next/link';
import { useRouter } from 'next/navigation'
 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [room, setRoom] = useState("");
  const router = useRouter()


  function hit() {
    console.log("Hello")
  }


  return (
    <>
      <Head>
        <title>Next Learning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Metting App</h1>

        <input type='text' placeholder='Enter Your Name' onChange={(e) => setRoom(e.target.value)}/>
        <button onClick={() => router.push(`/${room}`, { scroll: false })}>Submit</button>
        {/* <Button hit={hit} />
        <Link href={"/zia12345"}>To User Page</Link>
        <Link href={"/2022/12/06"}>Dynamic Routes</Link> */}
      </main>
    </>
  )
}
